### ISSUE TITLE
sam directory  already exists

### ISSUE THREAD

**Issue by sohams25** [Divelix/samat#3]
Hey, I am trying to use the script your have added for using SAM, for preprocessing.
It is throwing me this error, can you help me resolve this:

Loading vit_h on cuda device
Traceback (most recent call last):
  File "<>/samat/scripts/preprocess_dataset.py", line 39, in <module>
    sam = make_annotator(config["paths"]["sam_weights"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<>/samat/scripts/preprocess_dataset.py", line 20, in make_annotator
    sam = sam_model_registry[model_type](sam_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<>/lib/python3.12/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
           ^^^^^^^^^^^
  File "<>/lib/python3.12/site-packages/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'samat/example_dataset/sam'

**Comment by Divelix** [comment]
My bad, I made typo in `preprocess_dataset.py`. I just fixed it, so just pull main branch and it should work fine now.
